services:
  conduit-api:
    build:
      context: ./backend/domain
    container_name: conduit-api
    command: uvicorn conduit.app:app --host 0.0.0.0 --port 8080
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/database

volumes:
  db-data:
