services:
  conduit-gateway:
    build:
      context: ./backend/api-gateway
    container_name: conduit-gateway
    ports:
      - "8080:80"
    networks:
      - conduit-network
    depends_on:
      - conduit-api
      - conduit-users-api

  conduit-api:
    build:
      context: ./backend
      dockerfile: ./conduit-api/Dockerfile
    container_name: conduit-api
    command: uvicorn conduit.app:app --host 0.0.0.0 --port 8080
    env_file:
      - .env.docker
    ports:
      - "8081:8080"
    volumes:
      - db-data:/app/database
    networks:
      - conduit-network
    depends_on:
      conduit-rabbitmq:
        condition: service_healthy


  conduit-users-api:
    build:
      context: ./backend
      dockerfile: ./users-api/Dockerfile
    container_name: conduit-users-api
    command: uvicorn conduit.app:app --host 0.0.0.0 --port 8080
    env_file:
      - .env.docker
    ports:
      - "8082:8080"
    volumes:
      - users-db-data:/app/database
    networks:
      - conduit-network
    depends_on:
      conduit-rabbitmq:
        condition: service_healthy

  conduit-rabbitmq:
    build:
      context: ./backend/messaging
    container_name: conduit-rabbitmq
    hostname: conduit-rabbitmq
    env_file:
      - .env.docker
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - conduit-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s

networks:
  conduit-network:
    name: conduit-network

volumes:
  db-data:
  users-db-data:
