services:
  conduit-gateway:
    build:
      context: ./backend/api-gateway
    container_name: conduit-gateway
    ports:
      - "8080:80"
    networks:
      - conduit-network
    depends_on:
      - conduit-api

  conduit-api:
    build:
      context: ./backend/domain
    container_name: conduit-api
    command: uvicorn conduit.app:app --host 0.0.0.0 --port 8080
    env_file:
      - .env.docker
    ports:
      - "8081:8080"
    volumes:
      - db-data:/app/database
    networks:
      - conduit-network

networks:
  conduit-network:
    name: conduit-network

volumes:
  db-data:
