[lint]
select = [
    "A",
    "ARG",
    "ASYNC",
    "E",
    "ERA",
    "F",
    "FAST",
    "I",
    "N",
    "PERF",
    "PT",
    "RSE",
    "SIM",
]
ignore = [
    "E501", # Disable per https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
]
