[lint]
select = [
    "A",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "F",
    "FA",
    "FAST",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INT",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "RSE",
    "RET",
    "RUF",
    "S", # flake8-bandit
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TC",
    "TID",
    "TD",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "E501", # Disable per https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "S101", # Allow asserts globally (should be allowed for tests only).
    "PLR2004", # Disable magic constants globally (should be disabled for tests only).
]

[lint.flake8-bugbear]
# Allow default arguments like, e.g., `data: List[str] = fastapi.Query(None)`.
extend-immutable-calls = ["fastapi.Depends"]
