[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "conduit-shared"
requires-python = ">= 3.9"
version = "0.1.0"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.pyright]
extends = "../../pyproject.toml"
